#!/bin/bash
# Copyright 2020 Sebastian Wiesnser <sebastian@swsnr.de>

# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

set -euo pipefail

DEST="$(git rev-parse --show-toplevel)/screenshots/side-by-side.png"

montage "$@" -tile "$#x1" -geometry +0+0 "$DEST"
oxipng "$DEST"
